# Generated by Django 3.2.3 on 2021-06-22 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cookbook', '0004_auto_20210613_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('satisfaction', models.CharField(choices=[('Nul', "J'aime pas du tout"), ('Bof', "C'est bof"), ('Moyen', 'Ca va'), ('Top', "C'est bon"), ('Super', 'Vraiment succulent')], default='Moyen', max_length=5)),
                ('cookbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook.cookbook')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook.recipe')),
            ],
        ),
    ]
