# Generated by Django 3.2.3 on 2021-06-13 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0002_auto_20210613_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tagtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook.tagtype'),
        ),
    ]
