# Generated by Django 3.2.3 on 2021-06-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0003_auto_20210601_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookbook',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
