# Generated by Django 3.2.3 on 2021-06-01 09:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cookbook', '0004_alter_cookbook_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookbook',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='cookbook',
            unique_together={('name', 'user')},
        ),
    ]
