# Generated by Django 3.2.3 on 2021-06-02 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0007_alter_cookbook_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='measure',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cookbook.recipe'),
        ),
        migrations.AddField(
            model_name='recipeinfos',
            name='recipe',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cookbook.recipe'),
        ),
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('name', 'measure', 'quantity', 'recipe')},
        ),
        migrations.DeleteModel(
            name='Quantity',
        ),
    ]
