# Generated by Django 3.2.3 on 2021-06-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0012_alter_recipe_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measure',
            field=models.CharField(default='unité', max_length=200),
        ),
    ]
