# Generated by Django 3.2.3 on 2021-06-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimeLinkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_time_code', models.CharField(max_length=20)),
                ('expiry_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
