# Generated by Django 3.2.3 on 2021-06-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetimelinkmodel',
            name='expiry_time',
        ),
        migrations.AddField(
            model_name='onetimelinkmodel',
            name='use_count',
            field=models.IntegerField(default=0),
        ),
    ]
