# Generated by Django 3.2.3 on 2021-06-18 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20210615_0842'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OneTimeLinkModel',
        ),
    ]
